### ISSUE TITLE
每次都弹出语言选择框，体验非常差，选择过能记在localStorage或cookie里么？

### ISSUE THREAD

**Issue by caozenx** [openLuat/luatos-wiki#9]
<img width="502" alt="image" src="https://github.com/openLuat/luatos-wiki/assets/1514450/1afd048b-1981-4c75-9435-d75752779518">

**Comment by chenxuuu** [comment]
你的浏览器语言不是中文吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月22日(周五) 下午3:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [openLuat/luatos-wiki] 每次都弹出语言选择框，体验非常差，选择过能记在localStorage或cookie里么？ (Issue #9)

**Comment by caozenx** [comment]
> 你的浏览器语言不是中文吧？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年9月22日(周五) 下午3:52 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [openLuat/luatos-wiki] 每次都弹出语言选择框，体验非常差，选择过能记在localStorage或cookie里么？ (Issue #9) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是的  系统语言是英文， 浏览器跟系统

**Comment by chenxuuu** [comment]
后期会单独做一套英文站

**Comment by chenxuuu** [comment]
英文站已上线，该问题已不存在
